build: off

environment:
  MINICONDA: C:\\Miniconda37-x64

  matrix:
    - PYTHON_VERSION: 3.8
      NUMPY_VERSION: 1.18.1
      BUILD_ARTIFACT: "true"

    - PYTHON_VERSION: 3.7
      NUMPY_VERSION: 1.18.1
      BUILD_ARTIFACT: "false"

    - PYTHON_VERSION: 3.7
      NUMPY_VERSION: 1.17.4
      BUILD_ARTIFACT: "false"

    - PYTHON_VERSION: 3.7
      NUMPY_VERSION: 1.16.6
      BUILD_ARTIFACT: "false"
  
install:
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - "conda create -n test-environment python=%PYTHON_VERSION% numpy==%NUMPY_VERSION% scipy"
  - activate test-environment
  - python setup.py develop"

before_test:
  - pip install pytest
  - pip install pytest-cov
  
test_script:
  - pytest -v tests/ --cov=exampy/

after_test:
  - ps: |
      if ($env:BUILD_ARTIFACT -eq "true") {
        pip install wheel
        python setup.py bdist_wheel
        Get-ChildItem dist\*.whl | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      }
